### ISSUE TITLE
Facebook URL isn't working as of now

### ISSUE THREAD

**Issue by kubukoz** [spring-guides/gs-consuming-rest#10]
When you call a GET on http://graph.facebook.com/pivotalsoftware, you get an error:
```{
   "error": {
      "message": "An access token is required to request this resource.",
      "type": "OAuthException",
      "code": 104
   }
}```

Better find another example :)

**Comment by habuma** [comment]
Facebook has recently started requiring access tokens for all (or almost all) requests. In order to fix this, we'll need to find another API to code against. Stay tuned.

**Comment by gregturn** [comment]
I swapped Facebook service out with an internal one that we run. Enjoy!
