### ISSUE TITLE
Guide doesn't work in a plain IDE due to the use of Lombok

### ISSUE THREAD

**Issue by wilkinsona** [spring-guides/gs-consuming-rest#13]
Without Lombok, there's no `toString` on `Quote` so the log message reads:

```
2015-09-22 16:04:29.475  INFO 54815 --- [           main] hello.Application                        : hello.Quote@7582ff54
```

There also aren't any setters so Jackson's unable to perform any binding. That means that you can't even see the values if you use a debugger.

IMO, we shouldn't use Lombok in the Guides. It's extra setup that people have to do, and also extra "magic" that people have to understand.

**Comment by gregturn** [comment]
@dgomesbr I appreciate you coding up a solution, but I needed to also update the build files as well.

**Comment by dgomesbr** [comment]
@gregturn really forgot about the dependency (for both pom and gradle), please, put the toString() as well on your commit please.

About the docs, I saw the asciidoc including the source of the files, so I didn't find any related item for the publishing the docs or pushing a commit to it. (or the need to)

**Comment by gregturn** [comment]
How's about https://github.com/spring-guides/gs-consuming-rest/commit/123a71b3690d1969c689a4b85138da8ddf335a08?

**Comment by gregturn** [comment]
@dgomesbr The docs are automatically generated by spring.io (and cached from a github hook).

**Comment by dgomesbr** [comment]
@gregturn Nice! Thanks again for the clarification. :+1:
