### ISSUE TITLE
Text of guide refers incorrectly to Pivotal and Lombok

### ISSUE THREAD

**Issue by iambic69** [spring-guides/gs-consuming-rest#16]
The guide says "If all you need to know are Pivotal’s name, phone number, website URL, and what the pivotalsoftware page is about, then the following domain class should do fine:", but the example being used is quotes about Spring Boot, not Pivotal's web page.

After the example domain class, Quote.java, it says "It also uses Project Lombok’s @Data annotation, which provides a getter, a setter, a toString, and other supporting methods."  However, "@Data" is not used.

**Comment by gregturn** [comment]
Resolved via #15
