### ISSUE TITLE
HTML issue?

### ISSUE THREAD

**Issue by layik** [spring-guides/gs-consuming-rest#21]
The page does not show the contents of the READ.ME file properly or something else is not quite right.
https://spring.io/guides/gs/consuming-rest/
![1](https://cloud.githubusercontent.com/assets/408568/18872330/c6346fd6-84b1-11e6-93f2-92f511e8c0ed.png)

**Comment by gregturn** [comment]
Refreshed the cache. Guide now renders properly.
