### ISSUE TITLE
Source code for Application.java (Standalone Version) does not compile

### ISSUE THREAD

**Issue by Jens-OC** [spring-guides/gs-consuming-rest#26]
The example source code for the first version of the src/main/java/hello/Application.java (standalone version) does not contain the package declaration is is missing the imports as well. For that reason it does not compile directly. 

Though fixing the file is not a big issue it might confuse java newbies and I suggest to replace the existing example source code with the following one that compiles without errors:

```
package hello;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.client.RestTemplate;

public class Application {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    public static void main(String args[]) {
        RestTemplate restTemplate = new RestTemplate();
        Quote quote = restTemplate.getForObject("http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
        log.info(quote.toString());
    }
}
```

**Comment by gregturn** [comment]
Afraid I don't understand this issue.

https://github.com/spring-guides/gs-consuming-rest/blob/master/complete/src/main/java/hello/Application.java shows exactly what you're talking about.

**Comment by gregturn** [comment]
Executing `test/run.sh` against the whole repository, and everything passes.

**Comment by Jens-OC** [comment]
I'm talking about the sources presented on the website, not the ones that are packaged in the download section: 

![grafik](https://user-images.githubusercontent.com/31878186/30414157-7af4de12-9922-11e7-9376-70dc0898e9be.png)

Unlike the other source listings in this guide this one does not include the package declaration and imports. If the reader of the guide chooses to copy / paste the file contents instead of downloading the package this might result in issues. Sorry for missing to state this in the initial description.
