### ISSUE TITLE
RestTemplate is being deprecated.

### ISSUE THREAD

**Issue by dailytabs** [spring-guides/gs-consuming-rest#28]
According to https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html:

> NOTE: As of 5.0, the non-blocking, reactive org.springframework.web.reactive.client.WebClient offers a modern alternative to the RestTemplate with efficient support for both sync and async, as well as streaming scenarios. The RestTemplate will be deprecated in a future version and will not have major new features added going forward.

Anyone care to rewrite this guide for WebClient?

**Comment by UgmaDevelopment** [comment]
I came here to bring up this same thing, but as I'm just learning, I'm unsure how quickly it needs to be changed.

Regardless, thanks @dailytabs and @gregturn, @Buzzardo and others for your hard work!

**Comment by bosatsu** [comment]
https://gturnquist-quoters.cfapps.io/api/random returns 404 now.

**Comment by ssjlee93** [comment]
> https://gturnquist-quoters.cfapps.io/api/random returns 404, even in a browser.

Check out #47  . Someone posted a temporary workaround.

**Comment by Kumar2106** [comment]
I have heard in a youtube video, that yes it is going to be deprecated.

**Comment by dedeibel** [comment]
I was worried too but apparently the wording changed at some point. Does it mean that code that uses it is fine but it is not recommended for new code? Or is it actually just a matter of your requirement and taste?

`NOTE: As of 5.0 this class is in maintenance mode, with only minor requests for changes and bugs to be accepted going forward. Please, consider using the org.springframework.web.reactive.client.WebClient which has a more modern API and supports sync, async, and streaming scenarios.`

**Comment by rearl** [comment]
I noted the same as @dedeibel. So I'm curious to know what happens with `RestTemplate` in the future. To assess whether a migration to WebClient is (already) necessary or not.
Can anyone give us more information on this?

**Comment by Buzzardo** [comment]
As folks have noticed, the Spring Team plans to continue to make RestTemplate available as is (but only as-is - only something like a CVE would make us change it). If you need it, use it, but we do recommend WebClient as the modern replacement.
