### ISSUE TITLE
Typo in pom.xml example

### ISSUE THREAD

**Issue by Cvetomird91** [spring-guides/gs-consuming-rest#29]
Hello,

There's a typo in the Maven import in the Maven file:

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

The "boot" package is missing here.

**Comment by gregturn** [comment]
`spring-web` is the module from the Spring Framework that contains `RestTemplate`, which is used in the guide:

```
@Bean
public CommandLineRunner run(RestTemplate restTemplate) throws Exception {
	return args -> {
		Quote quote = restTemplate.getForObject(
				"http://gturnquist-quoters.cfapps.io/api/random", Quote.class);
		log.info(quote.toString());
	};
}
```
