### ISSUE TITLE
quoters is down

### ISSUE THREAD

**Issue by mohan3d** [spring-guides/gs-consuming-rest#47]
Tried to run the example but not working just realized [gturnquist-quoters](https://gturnquist-quoters.cfapps.io/api/random) is down, not sure if there is a mirror for this API or hosted somewhere else to update your example.

```Caused by: org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [404 Not Found: Requested route ('gturnquist-quoters.cfapps.io') does not exist```

**Comment by ottlinger** [comment]
Same here - http as well as https is not working anymore.

**Comment by aleksandar-trifunovic** [comment]
Now it's live. I had the same problem. 
https://quoters.apps.pcfone.io/api/random

**Comment by cmacho** [comment]
API is still down

**Comment by ArnaudKleinveld** [comment]
https://quoters.apps.pcfone.io/api/random times out in browser. Renders this demo useless unfortunately.

**Comment by ayan-b** [comment]
I am proxying a [single quote response](https://gistcdn.githack.com/ayan-b/ff0441b5a8d6c489b58659ffb849aff4/raw/e1c5ca10f7bea57edd793c4189ea8339de534b45/response.json) via [githack](https://raw.githack.com). This is a temporary solution and ideally, the quoter service should be fixed.

**Comment by srinivasbellarichenna** [comment]
@ayan-b , could you also post the usage code snippet?

**Comment by ayan-b** [comment]
Replace line 30 link with this link: https://gistcdn.githack.com/ayan-b/ff0441b5a8d6c489b58659ffb849aff4/raw/e1c5ca10f7bea57edd793c4189ea8339de534b45/response.json

https://github.com/spring-guides/gs-consuming-rest/blob/2b4168375caa4b2ff6227b332dace8e13ab7cfd1/complete/src/main/java/com/example/consumingrest/ConsumingRestApplication.java#L30

**Comment by Deewens** [comment]
Still down, the guide needs to be updated.

**Comment by jmcinerney** [comment]
Looks like that endpoint is still down. Was using this to help onboard someone, but came up with the workaround to have them modify their code and point their endpoint at the service they already built in https://spring.io/guides/gs/rest-service/

Seemed like a fun way to combine two projects :man_shrugging: :slightly_smiling_face:

**Comment by shyllenno** [comment]
It's been an year and half that "Quoters" is down, so why keep the guide "Consuming Rest Application" online? Just take it down... It is frustrating finishing a step by step and not being able to test it. Just take it down....

**Comment by HansMbua** [comment]
this 
https://gistcdn.githack.com/ayan-b/ff0441b5a8d6c489b58659ffb849aff4/raw/e1c5ca10f7bea57edd793c4189ea8339de534b45/response.json
works for me but dose not print the Quotes randomely

**Comment by Buzzardo** [comment]
Fixed by describing how to run the quoters application locally and connect to it on localhost.
