### ISSUE TITLE
A bit of literal error

### ISSUE THREAD

**Issue by Changuixin** [spring-guides/gs-consuming-rest#48]
[finishing-the-application](https://github.com/spring-guides/gs-consuming-rest#finishing-the-application)
Original sentence:
The **Initalizr** creates a class with a main() method. The following listing shows the class the **Initializr** creates...

Revised sentence:
The **initializer** creates a class with a main() method. The following listing shows the class the **initializer** creates...

**Comment by dsyer** [comment]
But "Initializr" is what we call it (https://github.com/spring-io/initializr), so I don't think this is an issue, unless I'm missing something.

**Comment by Changuixin** [comment]
Haha, I'm sorry. I just started to learn spring. When I saw a development tool called "spring initializer", I understood that it was a tool for creating projects. I'm sorry for the delay.
