### ISSUE TITLE
Wrong word `Initalizr` 

### ISSUE THREAD

**Issue by taehoonkange** [spring-guides/gs-consuming-rest#53]
I found the word  on line 111 in `README.adoc`.
```java
The Initalizr creates a class with a `main()` method. The following listing shows the
class the Initializr creates (at
`src/main/java/com/example/consumingrest/ConsumingRestApplication.java`):
```
Can you fix `initalizr` to `initialzr`

**Comment by Buzzardo** [comment]
Good catch. I'm going to leave it rather than fix it, though, as a good first issue for someone to take as their first contribution to Spring (a risk-free way to get started, basically). I have added the corresponding label.

**Comment by Buzzardo** [comment]
Fixed by https://github.com/spring-guides/gs-consuming-rest/pull/55
