### ISSUE TITLE
Failed to execute CommandLineRunner

### ISSUE THREAD

**Issue by ConfusedMerlin** [spring-guides/gs-consuming-rest#56]
As the title says... I clone you repo, say "mvnw spring-boot:run" and... that is the exception I get after it doenwloaded and compiled the app. 

This happens too if I build the projekt fresh with the Initializer and write every class myself. 

There is one thing, though, I have to run "mvn wrapper:wrapper"  before I can do anything, because this dev machine sits behind a company proxy. Would that be able to cause such an error?

**Comment by Buzzardo** [comment]
Fixed by https://github.com/spring-guides/gs-consuming-rest/pull/58
