### ISSUE TITLE
Potential null pointer access: The variable quote may be null at this location

### ISSUE THREAD

**Issue by vangotek** [spring-guides/gs-consuming-rest#59]
after updating boot to 3.1.4 this error occurs.
![NullPointer](https://github.com/spring-guides/gs-consuming-rest/assets/128784344/17d0ade9-b920-418d-ab05-aca4d7bacb60)

Potential null pointer access: The variable quote may be null at this location

log.info(quote.toString());

**Comment by Buzzardo** [comment]
To keep the code as simple as possible, we don't add usually null checks in the guides. In production code, though, it's certainly something to consider.
