### ISSUE TITLE
could not access http://localhost:8080/api/random

### ISSUE THREAD

**Issue by 43v3rn88b** [spring-guides/gs-consuming-rest#61]
org.springframework.web.client.HttpClientErrorException$NotFound: 404 : "{"timestamp":"2024-01-20T07:34:40.420+00:00","status":404,"error":"Not Found","path":"/api/random"}"

**Comment by Buzzardo** [comment]
You must run the application in the https://github.com/spring-guides/quoters repository in a local terminal. Then you can access it. When I do that, I get

`{"type":"success","value":{"id":5,"quote":"Spring Boot solves this problem. It gets rid of XML and wires up common components for me, so I don't have to spend hours scratching my head just to figure out how it's all pieced together."}}`
